# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bd.ui',
# licensing of 'bd.ui' applies.
#
# Created: Fri Aug 27 15:21:08 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(150, 24, 1041, 530))
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.label = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label.setGeometry(QtCore.QRect(470, 0, 471, 251))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("data/bd0.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_2.setGeometry(QtCore.QRect(470, 260, 131, 151))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("data/bd1.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_3.setGeometry(QtCore.QRect(610, 260, 161, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("data/bd2.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_4.setGeometry(QtCore.QRect(2, 2, 461, 501))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_6.setGeometry(QtCore.QRect(660, 270, 61, 21))
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.label_7 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_7.setGeometry(QtCore.QRect(2, 2, 431, 501))
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_8.setGeometry(QtCore.QRect(10, 68, 381, 91))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_9.setGeometry(QtCore.QRect(450, 20, 161, 151))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("data/bd3.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_10.setGeometry(QtCore.QRect(510, 0, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_11.setGeometry(QtCore.QRect(2, 162, 431, 71))
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_12.setGeometry(QtCore.QRect(2, 232, 431, 101))
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_13.setGeometry(QtCore.QRect(2, 332, 431, 71))
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label_14.setGeometry(QtCore.QRect(2, 402, 431, 101))
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.label_15 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_15.setGeometry(QtCore.QRect(2, 2, 431, 411))
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_16.setGeometry(QtCore.QRect(440, 220, 171, 161))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("data/bd4.png"))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_17.setGeometry(QtCore.QRect(8, 70, 401, 71))
        self.label_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_18.setGeometry(QtCore.QRect(20, 142, 401, 271))
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_19.setGeometry(QtCore.QRect(432, 2, 511, 181))
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_20.setGeometry(QtCore.QRect(440, 30, 341, 71))
        self.label_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_21.setGeometry(QtCore.QRect(460, 100, 461, 81))
        self.label_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_22.setGeometry(QtCore.QRect(500, 190, 61, 31))
        self.label_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.stackedWidget.addWidget(self.stackedWidgetPage3)
        self.stackedWidgetPage4 = QtWidgets.QWidget()
        self.stackedWidgetPage4.setObjectName("stackedWidgetPage4")
        self.label_26 = QtWidgets.QLabel(self.stackedWidgetPage4)
        self.label_26.setGeometry(QtCore.QRect(2, 2, 371, 141))
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.stackedWidgetPage4)
        self.label_27.setGeometry(QtCore.QRect(10, 180, 161, 151))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("data/bd5.png"))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.stackedWidgetPage4)
        self.label_28.setGeometry(QtCore.QRect(374, 0, 581, 531))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("data/bd6.png"))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.stackedWidgetPage4)
        self.label_29.setGeometry(QtCore.QRect(10, 60, 361, 81))
        self.label_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.stackedWidgetPage4)
        self.label_30.setGeometry(QtCore.QRect(63, 160, 61, 31))
        self.label_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.stackedWidget.addWidget(self.stackedWidgetPage4)
        self.stackedWidgetPage5 = QtWidgets.QWidget()
        self.stackedWidgetPage5.setObjectName("stackedWidgetPage5")
        self.label_31 = QtWidgets.QLabel(self.stackedWidgetPage5)
        self.label_31.setGeometry(QtCore.QRect(2, 2, 411, 241))
        self.label_31.setFrameShape(QtWidgets.QFrame.Box)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.stackedWidgetPage5)
        self.label_32.setGeometry(QtCore.QRect(10, 80, 401, 161))
        self.label_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.stackedWidgetPage5)
        self.label_33.setGeometry(QtCore.QRect(420, 30, 161, 151))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("data/bd7.png"))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.stackedWidgetPage5)
        self.label_34.setGeometry(QtCore.QRect(480, 20, 48, 13))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.stackedWidgetPage5)
        self.label_35.setGeometry(QtCore.QRect(2, 245, 381, 151))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("data/bd8.png"))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.stackedWidgetPage5)
        self.label_36.setGeometry(QtCore.QRect(420, 220, 611, 301))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("data/bdmiss1.jpg"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.stackedWidget.addWidget(self.stackedWidgetPage5)
        self.stackedWidgetPage6 = QtWidgets.QWidget()
        self.stackedWidgetPage6.setObjectName("stackedWidgetPage6")
        self.label_37 = QtWidgets.QLabel(self.stackedWidgetPage6)
        self.label_37.setGeometry(QtCore.QRect(2, 2, 381, 151))
        self.label_37.setFrameShape(QtWidgets.QFrame.Box)
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.stackedWidgetPage6)
        self.label_38.setGeometry(QtCore.QRect(20, 75, 351, 71))
        self.label_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.stackedWidgetPage6)
        self.label_39.setGeometry(QtCore.QRect(390, 10, 331, 71))
        self.label_39.setFrameShape(QtWidgets.QFrame.Box)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.stackedWidgetPage6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 154, 1041, 381))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(0, 0, 1031, 341))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("data/bdmiss5.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_42 = QtWidgets.QLabel(self.tab_8)
        self.label_42.setGeometry(QtCore.QRect(0, 0, 1021, 351))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("data/bdmiss2.jpg"))
        self.label_42.setScaledContents(False)
        self.label_42.setObjectName("label_42")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_43 = QtWidgets.QLabel(self.tab_9)
        self.label_43.setGeometry(QtCore.QRect(-2, -3, 1021, 361))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("data/bdmiss3.jpg"))
        self.label_43.setScaledContents(False)
        self.label_43.setObjectName("label_43")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_44 = QtWidgets.QLabel(self.tab_10)
        self.label_44.setGeometry(QtCore.QRect(-1, -2, 981, 201))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("data/bdmiss4.jpg"))
        self.label_44.setObjectName("label_44")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.label_41 = QtWidgets.QLabel(self.stackedWidgetPage6)
        self.label_41.setGeometry(QtCore.QRect(390, 80, 331, 71))
        self.label_41.setFrameShape(QtWidgets.QFrame.Box)
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.stackedWidget.addWidget(self.stackedWidgetPage6)
        self.stackedWidgetPage7 = QtWidgets.QWidget()
        self.stackedWidgetPage7.setObjectName("stackedWidgetPage7")
        self.label_45 = QtWidgets.QLabel(self.stackedWidgetPage7)
        self.label_45.setGeometry(QtCore.QRect(2, 2, 1031, 461))
        self.label_45.setFrameShape(QtWidgets.QFrame.Box)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.stackedWidgetPage7)
        self.label_46.setGeometry(QtCore.QRect(10, 70, 341, 71))
        self.label_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_46.setWordWrap(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.stackedWidgetPage7)
        self.label_47.setGeometry(QtCore.QRect(10, 150, 461, 301))
        self.label_47.setFrameShape(QtWidgets.QFrame.Box)
        self.label_47.setWordWrap(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.stackedWidgetPage7)
        self.label_48.setGeometry(QtCore.QRect(480, 90, 161, 151))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("data/bd13.png"))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.stackedWidgetPage7)
        self.label_49.setGeometry(QtCore.QRect(480, 250, 491, 201))
        self.label_49.setFrameShape(QtWidgets.QFrame.Box)
        self.label_49.setWordWrap(True)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.stackedWidgetPage7)
        self.label_50.setGeometry(QtCore.QRect(545, 76, 48, 13))
        self.label_50.setObjectName("label_50")
        self.stackedWidget.addWidget(self.stackedWidgetPage7)
        self.stackedWidgetPage8 = QtWidgets.QWidget()
        self.stackedWidgetPage8.setObjectName("stackedWidgetPage8")
        self.label_51 = QtWidgets.QLabel(self.stackedWidgetPage8)
        self.label_51.setGeometry(QtCore.QRect(2, 2, 371, 191))
        self.label_51.setFrameShape(QtWidgets.QFrame.Box)
        self.label_51.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_51.setWordWrap(True)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.stackedWidgetPage8)
        self.label_52.setGeometry(QtCore.QRect(12, 82, 351, 101))
        self.label_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_52.setWordWrap(True)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.stackedWidgetPage8)
        self.label_53.setGeometry(QtCore.QRect(20, 228, 161, 161))
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("data/bd14.png"))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.stackedWidgetPage8)
        self.label_54.setGeometry(QtCore.QRect(70, 220, 81, 20))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.stackedWidgetPage8)
        self.label_55.setGeometry(QtCore.QRect(390, 10, 371, 501))
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("data/bd15.png"))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.stackedWidgetPage8)
        self.label_56.setGeometry(QtCore.QRect(780, 0, 251, 521))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("data/bd16.png"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.stackedWidget.addWidget(self.stackedWidgetPage8)
        self.stackedWidgetPage9 = QtWidgets.QWidget()
        self.stackedWidgetPage9.setObjectName("stackedWidgetPage9")
        self.label_57 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_57.setGeometry(QtCore.QRect(2, 2, 311, 201))
        self.label_57.setFrameShape(QtWidgets.QFrame.Box)
        self.label_57.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_57.setWordWrap(True)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_58.setGeometry(QtCore.QRect(12, 102, 281, 91))
        self.label_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_58.setWordWrap(True)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_59.setGeometry(QtCore.QRect(246, 114, 41, 20))
        self.label_59.setText("")
        self.label_59.setPixmap(QtGui.QPixmap("data/bdmiss6.png"))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_60.setGeometry(QtCore.QRect(490, 30, 301, 231))
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap("data/bd18.png"))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_61.setGeometry(QtCore.QRect(-10, 280, 351, 241))
        self.label_61.setText("")
        self.label_61.setPixmap(QtGui.QPixmap("data/bd19.png"))
        self.label_61.setScaledContents(False)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_62.setGeometry(QtCore.QRect(332, 289, 371, 231))
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("data/bd20.png"))
        self.label_62.setObjectName("label_62")
        self.label_68 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_68.setGeometry(QtCore.QRect(320, 20, 161, 151))
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap("data/bd17.png"))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.stackedWidgetPage9)
        self.label_69.setGeometry(QtCore.QRect(360, 8, 101, 16))
        self.label_69.setObjectName("label_69")
        self.stackedWidget.addWidget(self.stackedWidgetPage9)
        self.stackedWidgetPage10 = QtWidgets.QWidget()
        self.stackedWidgetPage10.setObjectName("stackedWidgetPage10")
        self.label_63 = QtWidgets.QLabel(self.stackedWidgetPage10)
        self.label_63.setGeometry(QtCore.QRect(2, 2, 391, 211))
        self.label_63.setFrameShape(QtWidgets.QFrame.Box)
        self.label_63.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_63.setWordWrap(True)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.stackedWidgetPage10)
        self.label_64.setGeometry(QtCore.QRect(10, 70, 371, 131))
        self.label_64.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_64.setWordWrap(True)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.stackedWidgetPage10)
        self.label_65.setGeometry(QtCore.QRect(400, 0, 631, 521))
        self.label_65.setText("")
        self.label_65.setPixmap(QtGui.QPixmap("data/bdmiss7.png"))
        self.label_65.setScaledContents(True)
        self.label_65.setObjectName("label_65")
        self.label_70 = QtWidgets.QLabel(self.stackedWidgetPage10)
        self.label_70.setGeometry(QtCore.QRect(10, 250, 161, 151))
        self.label_70.setText("")
        self.label_70.setPixmap(QtGui.QPixmap("data/bd22.png"))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.stackedWidgetPage10)
        self.label_71.setGeometry(QtCore.QRect(20, 220, 151, 31))
        self.label_71.setWordWrap(True)
        self.label_71.setObjectName("label_71")
        self.stackedWidget.addWidget(self.stackedWidgetPage10)
        self.stackedWidgetPage11 = QtWidgets.QWidget()
        self.stackedWidgetPage11.setObjectName("stackedWidgetPage11")
        self.label_66 = QtWidgets.QLabel(self.stackedWidgetPage11)
        self.label_66.setGeometry(QtCore.QRect(2, 2, 331, 251))
        self.label_66.setFrameShape(QtWidgets.QFrame.Box)
        self.label_66.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_66.setWordWrap(True)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.stackedWidgetPage11)
        self.label_67.setGeometry(QtCore.QRect(10, 90, 311, 91))
        self.label_67.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_67.setWordWrap(True)
        self.label_67.setObjectName("label_67")
        self.label_72 = QtWidgets.QLabel(self.stackedWidgetPage11)
        self.label_72.setGeometry(QtCore.QRect(4, 273, 161, 151))
        self.label_72.setText("")
        self.label_72.setPixmap(QtGui.QPixmap("data/d26.png"))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.stackedWidgetPage11)
        self.label_73.setGeometry(QtCore.QRect(60, 260, 61, 16))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.stackedWidgetPage11)
        self.label_74.setGeometry(QtCore.QRect(320, -20, 551, 561))
        self.label_74.setText("")
        self.label_74.setPixmap(QtGui.QPixmap("data/bd27.png"))
        self.label_74.setScaledContents(True)
        self.label_74.setObjectName("label_74")
        self.stackedWidget.addWidget(self.stackedWidgetPage11)
        self.stackedWidgetPage12 = QtWidgets.QWidget()
        self.stackedWidgetPage12.setObjectName("stackedWidgetPage12")
        self.label_75 = QtWidgets.QLabel(self.stackedWidgetPage12)
        self.label_75.setGeometry(QtCore.QRect(2, 2, 331, 181))
        self.label_75.setFrameShape(QtWidgets.QFrame.Box)
        self.label_75.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_75.setWordWrap(True)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.stackedWidgetPage12)
        self.label_76.setGeometry(QtCore.QRect(10, 100, 311, 71))
        self.label_76.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_76.setWordWrap(True)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.stackedWidgetPage12)
        self.label_77.setGeometry(QtCore.QRect(0, 210, 161, 151))
        self.label_77.setText("")
        self.label_77.setPixmap(QtGui.QPixmap("data/bd28.png"))
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.stackedWidgetPage12)
        self.label_78.setGeometry(QtCore.QRect(63, 200, 47, 13))
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.stackedWidgetPage12)
        self.label_79.setGeometry(QtCore.QRect(360, 20, 631, 491))
        self.label_79.setText("")
        self.label_79.setPixmap(QtGui.QPixmap("data/bdmiss8.png"))
        self.label_79.setScaledContents(True)
        self.label_79.setObjectName("label_79")
        self.stackedWidget.addWidget(self.stackedWidgetPage12)
        self.stackedWidgetPage13 = QtWidgets.QWidget()
        self.stackedWidgetPage13.setObjectName("stackedWidgetPage13")
        self.label_83 = QtWidgets.QLabel(self.stackedWidgetPage13)
        self.label_83.setGeometry(QtCore.QRect(2, 2, 411, 121))
        self.label_83.setFrameShape(QtWidgets.QFrame.Box)
        self.label_83.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_83.setWordWrap(True)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.stackedWidgetPage13)
        self.label_84.setGeometry(QtCore.QRect(40, 70, 311, 51))
        self.label_84.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_84.setWordWrap(True)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.stackedWidgetPage13)
        self.label_85.setGeometry(QtCore.QRect(10, 140, 161, 151))
        self.label_85.setText("")
        self.label_85.setPixmap(QtGui.QPixmap("data/bd31.png"))
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.stackedWidgetPage13)
        self.label_86.setGeometry(QtCore.QRect(84, 130, 47, 13))
        self.label_86.setObjectName("label_86")
        self.stackedWidget.addWidget(self.stackedWidgetPage13)
        self.stackedWidgetPage14 = QtWidgets.QWidget()
        self.stackedWidgetPage14.setObjectName("stackedWidgetPage14")
        self.label_87 = QtWidgets.QLabel(self.stackedWidgetPage14)
        self.label_87.setGeometry(QtCore.QRect(2, 2, 301, 131))
        self.label_87.setFrameShape(QtWidgets.QFrame.Box)
        self.label_87.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_87.setWordWrap(True)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.stackedWidgetPage14)
        self.label_88.setGeometry(QtCore.QRect(20, 90, 261, 41))
        self.label_88.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_88.setWordWrap(True)
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.stackedWidgetPage14)
        self.label_89.setGeometry(QtCore.QRect(60, 160, 191, 181))
        self.label_89.setText("")
        self.label_89.setPixmap(QtGui.QPixmap("data/bdmiss6.jpg"))
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.stackedWidgetPage14)
        self.label_90.setGeometry(QtCore.QRect(120, 140, 81, 16))
        self.label_90.setObjectName("label_90")
        self.stackedWidget.addWidget(self.stackedWidgetPage14)
        self.stackedWidgetPage15 = QtWidgets.QWidget()
        self.stackedWidgetPage15.setObjectName("stackedWidgetPage15")
        self.label_91 = QtWidgets.QLabel(self.stackedWidgetPage15)
        self.label_91.setGeometry(QtCore.QRect(2, 2, 441, 151))
        self.label_91.setFrameShape(QtWidgets.QFrame.Box)
        self.label_91.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.stackedWidgetPage15)
        self.label_92.setGeometry(QtCore.QRect(20, 70, 421, 81))
        self.label_92.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_92.setWordWrap(True)
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.stackedWidgetPage15)
        self.label_93.setGeometry(QtCore.QRect(10, 290, 181, 181))
        self.label_93.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_93.setText("")
        self.label_93.setPixmap(QtGui.QPixmap("data/bdmiss7.jpg"))
        self.label_93.setObjectName("label_93")
        self.tabWidget = QtWidgets.QTabWidget(self.stackedWidgetPage15)
        self.tabWidget.setGeometry(QtCore.QRect(450, 50, 591, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_94 = QtWidgets.QLabel(self.tab)
        self.label_94.setGeometry(QtCore.QRect(0, 10, 571, 371))
        self.label_94.setText("")
        self.label_94.setPixmap(QtGui.QPixmap("data/bdmiss9.jpg"))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName("label_94")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 121))
        self.groupBox.setObjectName("groupBox")
        self.label_95 = QtWidgets.QLabel(self.groupBox)
        self.label_95.setGeometry(QtCore.QRect(6, 13, 161, 101))
        self.label_95.setText("")
        self.label_95.setPixmap(QtGui.QPixmap("data/Новая папка/down1.jpg"))
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.groupBox)
        self.label_96.setGeometry(QtCore.QRect(164, 13, 151, 101))
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap("data/Новая папка/down2.jpg"))
        self.label_96.setObjectName("label_96")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 321, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_97 = QtWidgets.QLabel(self.groupBox_2)
        self.label_97.setGeometry(QtCore.QRect(6, 13, 161, 101))
        self.label_97.setText("")
        self.label_97.setPixmap(QtGui.QPixmap("data/Новая папка/up1.jpg"))
        self.label_97.setObjectName("label_97")
        self.label_99 = QtWidgets.QLabel(self.groupBox_2)
        self.label_99.setGeometry(QtCore.QRect(164, 13, 151, 101))
        self.label_99.setText("")
        self.label_99.setPixmap(QtGui.QPixmap("data/Новая папка/up2.jpg"))
        self.label_99.setObjectName("label_99")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 321, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_102 = QtWidgets.QLabel(self.groupBox_3)
        self.label_102.setGeometry(QtCore.QRect(6, 13, 161, 101))
        self.label_102.setText("")
        self.label_102.setPixmap(QtGui.QPixmap("data/Новая папка/left1.jpg"))
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.groupBox_3)
        self.label_103.setGeometry(QtCore.QRect(164, 13, 151, 101))
        self.label_103.setText("")
        self.label_103.setPixmap(QtGui.QPixmap("data/Новая папка/left2.jpg"))
        self.label_103.setObjectName("label_103")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(370, 10, 171, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_106 = QtWidgets.QLabel(self.groupBox_4)
        self.label_106.setGeometry(QtCore.QRect(6, 13, 161, 101))
        self.label_106.setText("")
        self.label_106.setPixmap(QtGui.QPixmap("data/Новая папка/right1.jpg"))
        self.label_106.setObjectName("label_106")
        self.label_107 = QtWidgets.QLabel(self.groupBox_4)
        self.label_107.setGeometry(QtCore.QRect(7, 112, 151, 101))
        self.label_107.setText("")
        self.label_107.setPixmap(QtGui.QPixmap("data/Новая папка/right2.jpg"))
        self.label_107.setObjectName("label_107")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_98 = QtWidgets.QLabel(self.stackedWidgetPage15)
        self.label_98.setGeometry(QtCore.QRect(480, 15, 481, 21))
        self.label_98.setObjectName("label_98")
        self.label_108 = QtWidgets.QLabel(self.stackedWidgetPage15)
        self.label_108.setGeometry(QtCore.QRect(87, 275, 47, 13))
        self.label_108.setObjectName("label_108")
        self.stackedWidget.addWidget(self.stackedWidgetPage15)
        self.stackedWidgetPage16 = QtWidgets.QWidget()
        self.stackedWidgetPage16.setObjectName("stackedWidgetPage16")
        self.label_80 = QtWidgets.QLabel(self.stackedWidgetPage16)
        self.label_80.setGeometry(QtCore.QRect(2, 2, 291, 291))
        self.label_80.setFrameShape(QtWidgets.QFrame.Box)
        self.label_80.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_80.setWordWrap(True)
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.stackedWidgetPage16)
        self.label_81.setGeometry(QtCore.QRect(20, 100, 261, 201))
        self.label_81.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_81.setWordWrap(True)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.stackedWidgetPage16)
        self.label_82.setGeometry(QtCore.QRect(10, 310, 241, 111))
        self.label_82.setText("")
        self.label_82.setPixmap(QtGui.QPixmap("data/bdmiss5.jpg"))
        self.label_82.setObjectName("label_82")
        self.label_109 = QtWidgets.QLabel(self.stackedWidgetPage16)
        self.label_109.setGeometry(QtCore.QRect(110, 303, 61, 16))
        self.label_109.setObjectName("label_109")
        self.stackedWidget.addWidget(self.stackedWidgetPage16)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_110 = QtWidgets.QLabel(self.page)
        self.label_110.setGeometry(QtCore.QRect(2, 2, 361, 61))
        self.label_110.setFrameShape(QtWidgets.QFrame.Box)
        self.label_110.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_110.setObjectName("label_110")
        self.label_111 = QtWidgets.QLabel(self.page)
        self.label_111.setGeometry(QtCore.QRect(10, 100, 301, 311))
        self.label_111.setText("")
        self.label_111.setPixmap(QtGui.QPixmap("data/bdmiss10.jpg"))
        self.label_111.setObjectName("label_111")
        self.label_112 = QtWidgets.QLabel(self.page)
        self.label_112.setGeometry(QtCore.QRect(120, 90, 47, 13))
        self.label_112.setObjectName("label_112")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_113 = QtWidgets.QLabel(self.page_2)
        self.label_113.setGeometry(QtCore.QRect(2, 2, 321, 71))
        self.label_113.setFrameShape(QtWidgets.QFrame.Box)
        self.label_113.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_113.setWordWrap(True)
        self.label_113.setObjectName("label_113")
        self.label_114 = QtWidgets.QLabel(self.page_2)
        self.label_114.setGeometry(QtCore.QRect(0, 100, 351, 421))
        self.label_114.setText("")
        self.label_114.setPixmap(QtGui.QPixmap("data/bdmiss11.jpg"))
        self.label_114.setScaledContents(True)
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.page_2)
        self.label_115.setGeometry(QtCore.QRect(150, 86, 47, 13))
        self.label_115.setObjectName("label_115")
        self.stackedWidget.addWidget(self.page_2)
        self.pb0 = QtWidgets.QPushButton(self.centralwidget)
        self.pb0.setGeometry(QtCore.QRect(2, 25, 141, 23))
        self.pb0.setStyleSheet("")
        self.pb0.setObjectName("pb0")
        self.pb2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb2.setGeometry(QtCore.QRect(2, 73, 141, 23))
        self.pb2.setObjectName("pb2")
        self.pb3 = QtWidgets.QPushButton(self.centralwidget)
        self.pb3.setGeometry(QtCore.QRect(2, 97, 141, 23))
        self.pb3.setObjectName("pb3")
        self.pb4 = QtWidgets.QPushButton(self.centralwidget)
        self.pb4.setGeometry(QtCore.QRect(2, 121, 141, 23))
        self.pb4.setObjectName("pb4")
        self.pb6 = QtWidgets.QPushButton(self.centralwidget)
        self.pb6.setGeometry(QtCore.QRect(2, 169, 141, 23))
        self.pb6.setObjectName("pb6")
        self.pb1 = QtWidgets.QPushButton(self.centralwidget)
        self.pb1.setGeometry(QtCore.QRect(2, 49, 141, 23))
        self.pb1.setObjectName("pb1")
        self.pb8 = QtWidgets.QPushButton(self.centralwidget)
        self.pb8.setGeometry(QtCore.QRect(2, 217, 141, 23))
        self.pb8.setObjectName("pb8")
        self.pb7 = QtWidgets.QPushButton(self.centralwidget)
        self.pb7.setGeometry(QtCore.QRect(2, 193, 141, 23))
        self.pb7.setObjectName("pb7")
        self.pb13 = QtWidgets.QPushButton(self.centralwidget)
        self.pb13.setGeometry(QtCore.QRect(2, 337, 141, 23))
        self.pb13.setObjectName("pb13")
        self.pb12 = QtWidgets.QPushButton(self.centralwidget)
        self.pb12.setGeometry(QtCore.QRect(2, 313, 141, 23))
        self.pb12.setObjectName("pb12")
        self.pb10 = QtWidgets.QPushButton(self.centralwidget)
        self.pb10.setGeometry(QtCore.QRect(2, 265, 141, 23))
        self.pb10.setObjectName("pb10")
        self.pb9 = QtWidgets.QPushButton(self.centralwidget)
        self.pb9.setGeometry(QtCore.QRect(2, 241, 141, 23))
        self.pb9.setObjectName("pb9")
        self.pb11 = QtWidgets.QPushButton(self.centralwidget)
        self.pb11.setGeometry(QtCore.QRect(2, 289, 141, 23))
        self.pb11.setObjectName("pb11")
        self.pb14 = QtWidgets.QPushButton(self.centralwidget)
        self.pb14.setGeometry(QtCore.QRect(2, 361, 141, 23))
        self.pb14.setObjectName("pb14")
        self.pb16 = QtWidgets.QPushButton(self.centralwidget)
        self.pb16.setGeometry(QtCore.QRect(2, 409, 141, 23))
        self.pb16.setObjectName("pb16")
        self.pb17 = QtWidgets.QPushButton(self.centralwidget)
        self.pb17.setGeometry(QtCore.QRect(2, 433, 141, 23))
        self.pb17.setObjectName("pb17")
        self.pb15 = QtWidgets.QPushButton(self.centralwidget)
        self.pb15.setGeometry(QtCore.QRect(2, 385, 141, 23))
        self.pb15.setObjectName("pb15")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(2, 2, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_23.setFont(font)
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(3, 576, 221, 21))
        self.label_24.setFrameShape(QtWidgets.QFrame.Box)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(225, 576, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_25.setFont(font)
        self.label_25.setFrameShape(QtWidgets.QFrame.Box)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.pbDiscord = QtWidgets.QPushButton(self.centralwidget)
        self.pbDiscord.setGeometry(QtCore.QRect(406, 575, 101, 23))
        self.pbDiscord.setObjectName("pbDiscord")
        self.pb5 = QtWidgets.QPushButton(self.centralwidget)
        self.pb5.setGeometry(QtCore.QRect(2, 145, 141, 23))
        self.pb5.setObjectName("pb5")
        self.lb0 = QtWidgets.QLabel(self.centralwidget)
        self.lb0.setGeometry(QtCore.QRect(3, 26, 24, 21))
        self.lb0.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb0.setObjectName("lb0")
        self.lb1 = QtWidgets.QLabel(self.centralwidget)
        self.lb1.setGeometry(QtCore.QRect(3, 50, 24, 21))
        self.lb1.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb1.setObjectName("lb1")
        self.lb2 = QtWidgets.QLabel(self.centralwidget)
        self.lb2.setGeometry(QtCore.QRect(3, 74, 24, 21))
        self.lb2.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb2.setObjectName("lb2")
        self.lb3 = QtWidgets.QLabel(self.centralwidget)
        self.lb3.setGeometry(QtCore.QRect(3, 98, 24, 21))
        self.lb3.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb3.setObjectName("lb3")
        self.lb4 = QtWidgets.QLabel(self.centralwidget)
        self.lb4.setGeometry(QtCore.QRect(3, 122, 24, 21))
        self.lb4.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb4.setObjectName("lb4")
        self.lb5 = QtWidgets.QLabel(self.centralwidget)
        self.lb5.setGeometry(QtCore.QRect(3, 146, 24, 21))
        self.lb5.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb5.setObjectName("lb5")
        self.lb8 = QtWidgets.QLabel(self.centralwidget)
        self.lb8.setGeometry(QtCore.QRect(3, 218, 24, 21))
        self.lb8.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb8.setObjectName("lb8")
        self.lb9 = QtWidgets.QLabel(self.centralwidget)
        self.lb9.setGeometry(QtCore.QRect(3, 242, 24, 21))
        self.lb9.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb9.setObjectName("lb9")
        self.lb6 = QtWidgets.QLabel(self.centralwidget)
        self.lb6.setGeometry(QtCore.QRect(3, 170, 24, 21))
        self.lb6.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb6.setObjectName("lb6")
        self.lb7 = QtWidgets.QLabel(self.centralwidget)
        self.lb7.setGeometry(QtCore.QRect(3, 194, 24, 21))
        self.lb7.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb7.setObjectName("lb7")
        self.lb12 = QtWidgets.QLabel(self.centralwidget)
        self.lb12.setGeometry(QtCore.QRect(3, 314, 24, 21))
        self.lb12.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb12.setObjectName("lb12")
        self.lb17 = QtWidgets.QLabel(self.centralwidget)
        self.lb17.setGeometry(QtCore.QRect(3, 434, 24, 21))
        self.lb17.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb17.setObjectName("lb17")
        self.lb13 = QtWidgets.QLabel(self.centralwidget)
        self.lb13.setGeometry(QtCore.QRect(3, 338, 24, 21))
        self.lb13.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb13.setObjectName("lb13")
        self.lb10 = QtWidgets.QLabel(self.centralwidget)
        self.lb10.setGeometry(QtCore.QRect(3, 266, 24, 21))
        self.lb10.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb10.setObjectName("lb10")
        self.lb11 = QtWidgets.QLabel(self.centralwidget)
        self.lb11.setGeometry(QtCore.QRect(3, 290, 24, 21))
        self.lb11.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb11.setObjectName("lb11")
        self.lb15 = QtWidgets.QLabel(self.centralwidget)
        self.lb15.setGeometry(QtCore.QRect(3, 386, 24, 21))
        self.lb15.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb15.setObjectName("lb15")
        self.lb16 = QtWidgets.QLabel(self.centralwidget)
        self.lb16.setGeometry(QtCore.QRect(3, 410, 24, 21))
        self.lb16.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb16.setObjectName("lb16")
        self.lb14 = QtWidgets.QLabel(self.centralwidget)
        self.lb14.setGeometry(QtCore.QRect(3, 362, 24, 21))
        self.lb14.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.lb14.setObjectName("lb14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Обезвреживание Бомб:</span><br/>Бомба взрывается, когда её обратный таймер доходит до 0:00 или когда было зафиксировано слишком много ошибок.<br/><br/>Единственный способ обезвредить бомбу - это обезвредить все её модули, прежде чем на таймере кончится время.<br/><br/><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Модули:</span><br/>Каждая бомба включает в себя до 11 модулей, которые необходимо обезвредить.<br/>Каждый модуль автономен, их можно обезвреживать в любом порядке.<br/><br/>Модули можно определить по светодиоду в правом верхнем углу. Горящий зелёным светодиод указывает, что модуль уже обезврежен.<br/>Для обезвреживания бомбы необходимо обезвредить все модули.<br/><br/><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Ошибки:</span><br/>Если сапёр допускает ошибку, это будет отображено на индикаторе ошибок над обратным таймером.<br/><br/>Бомбы с индикатором ошибок взрываются на третьей ошибке. С каждой новой допущенной ошибкой время на таймере будет отсчитываться быстрее.<br/><br/>Если над таймером нет индиктаора, то бомба взорвётся с первой же ошибкой, не оставляя шансов на оплошности.<br/><br/><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Сбор информации:</span><br/>Некоторые инструкции по обезвреживанию требуют определённой информации о бомбе, например, её серийный номер.<br/><br/>Подобная информация обычно располагается сверху, снизу или по бокам бомбы. Смотрите приложения А, Б и В для соответствующих инструкций, полезных при обезвреживании определённых модулей.</p></body></html>", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Модуль</span></p></body></html>", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Провода:</span><br/><span style=\" font-size:9pt; font-style:italic;\">Провода - кровь электроники! Стоп, нет, электричество - кровь. Провода, скорее, артерии. Вены? Неважно...</span></p></body></html>", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">- Модуль содержит от 3 до 6 проводов.<br/>- Только </span><span style=\" font-size:10pt; text-decoration: underline;\">один</span><span style=\" font-size:10pt;\"> правильный провод необходимо перерезать для обезвреживания модуля.<br/>- Нумерация проводов отсчитывается, начиная от верхнего.</span></p></body></html>", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Провода", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">3 провода:</span><br/>Если нет красных проводов, режьте второй.<br/>Иначе, если последний провод белый, режьте последний.<br/>Иначе, если синих проводов больше, чем один, режьте последний синий.<br/>Иначе режьте последний.</p></body></html>", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">4 провода:</span><br/>Если красных проводов больше, чем один, и последняя цифра серийного номера нечётная, режьте последний красный.<br/>Иначе, если последний провод жёлтый, а красных нет, режьте первый.<br/>Иначе, если синий провод всего и только один, режьте первый.<br/>Иначе, если жёлтых проводов больше, чем один, режьте последний.<br/>Иначе режьте второй.</p></body></html>", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">5 проводов:</span><br/>Если последний провод чёртый, и последняя цифра серийного номера нечётная, режьте четвёртый.<br/>Иначе, если красный провод всего и только один, а жёлтых больше, чем один, режьте первый.<br/>Иначе, если чёрных проводов нет, режьте второй.<br/>Иначе режьте первый.</p></body></html>", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">6 проводов:</span><br/>Если жёлтых проводов нет, и последняя цифра серийного номера нечётная, режьте третий.<br/>Иначе, если жёлтый провод всего и только один, а белых проводов больше, чем один, режьте четвёртый.<br/>Иначе, если красных проводов нет, режьте последний.<br/>Иначе режьте четвёртый.</p></body></html>", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Кнопка:</span><br/><span style=\" font-style:italic;\">Кажется, что если на кнопке написано, что её нужно нажать, то тут и думать не о чем.<br/>Вот из-за такого люди и взрываются.</span></p></body></html>", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Определение индикатора - см. приложение А.<br/>Определение батареи - см. приложение Б.<br/><br/>Следуйте следующим правилам в том порядке, в котором они указаны. Выполняйте первое подходящее действие:</p></body></html>", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>1. Если кнопка синяя, а на кнопке написано &quot;Прервать&quot;, задержите кнопку и смотрите пункт &quot;Удержание кнопки&quot;.<br/><br/>2. Если на бомбе больше 1 батареи, а на кнопке написано &quot;Взорвать&quot;, нажмите и резко отпустите кнопку.<br/><br/>3. Если кнопка белая, а на корпусе бомбы есть горящий индикатор &quot;CAR&quot;, задержите кнопку и смотрите пункт &quot;Удержание кнопки&quot;.<br/><br/>4. Если на бомбе больше 2 батарей, а на корпусе бомбы есть горящий индикатор &quot;FRK&quot;, нажмите и резко отпустите кнопку.<br/><br/>5. Если кнопка жёлтая, задержите кнопку и смотрите пункт &quot;Удержание кнопки&quot;.<br/><br/>6. Если кнопка красная, а на кнопке написано &quot;Держать&quot;, нажмите и резко отпустите кнопку.<br/><br/>7. Если не подходит ни одно из вышеперечисленных правил, задержите кнопку и смотрите пункт &quot;Удержание кнопки&quot;.</p></body></html>", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Удержание кнопки:</span></p></body></html>", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Если вы начинаете удерживать кнопку, на правой стороне модуля зажжётся цветная полоска. В зависимости от её цвета вам нужно отпустить кнопку в определённый момент времени:</p></body></html>", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- <span style=\" text-decoration: underline;\">Синяя полоса:</span> отпустите, когда любая цифра обратного таймера будет равна 4.<br/>- <span style=\" text-decoration: underline;\">Белая полоска:</span> отпустите, когда любая цифра обратного таймера будет равна 1.<br/>- <span style=\" text-decoration: underline;\">Жёлтая полоска:</span> отпустите, когда любая цифра обратного таймера будет равна 5.<br/>- <span style=\" text-decoration: underline;\">Полоска любого другого цвета:</span> отпустите, когда любая цифра обратного таймера будет равна 1.</p></body></html>", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Кнопка", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Клавиатура:</span><br/><span style=\" font-style:italic;\">Не знаю, что это за крючки, но подозреваю, что они какие-то оккультные.</span></p></body></html>", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Лишь один из столбцов ниже содержит все четыре символа с клавиатуры.</p><p>- Нажмите четыре клавиши в том порядке, в котором эти символы расположены в соответствующем столбце сверху вниз.</p></body></html>", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Клавиатура", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">&quot;Саймон&quot; aka &quot;Делай как я&quot;:</span></p><p><span style=\" font-style:italic;\">Это какая-то детская игрушка, где нужно было повторять то, что светится, только это какая-то подделка, которую наверняка купили в магазине &quot;всё по пятьдесят&quot;.</span></p></body></html>", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>1. Загорается одна из цветных кнопок.</p><p>2. используя подходящую таблицу снизу, нажмите на кнопку соответствующего цвета.</p><p>3. Загорится та же кнопка, что и в начале, а за ней ещё одна.</p><p>Повторите эту последовательность в том же порядке, используя таблицу цветов.</p><p>4. Последовательность будет удлиняться после каждой успешно введённой последовательности, пока модуль не будет обезврежен.</p></body></html>", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Саймон", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">&quot;Слова&quot; aka &quot;Меня зовут Авас, а вас?&quot;:<br/></span><span style=\" font-style:italic;\">Эту головоломку как будто бы выдрали из комедийной репризы, что было смешно, не будь она соединена с бомбой. Буду краток, а то слова всё усложняют.</span></p></body></html>", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>1. Зачитайте слово на экране и определите в шаге 1, какую кнопку следует <span style=\" text-decoration: underline;\">прочитать</span>.<br/>2. Используя слово с этой кнопки, определите в шаге 2, какую кнопку следует <span style=\" text-decoration: underline;\">нажать</span>.<br/>3. Повторяйте, пока не обезвредите модуль.</p></body></html>", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">1 шаг:</span></p><p>В зависимости от слова на экране <span style=\" text-decoration: underline;\">прочитайте</span> слово на определяемой ниже кнопке и перейдите к шагу 2.</p></body></html>", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QtWidgets.QApplication.translate("MainWindow", "1 шаг", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QtWidgets.QApplication.translate("MainWindow", "2 шаг 1/3", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QtWidgets.QApplication.translate("MainWindow", "2 шаг 2/3", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QtWidgets.QApplication.translate("MainWindow", "2 шаг 3/3", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">2 шаг:</span></p><p>Используя слово из 1 шага, <span style=\" text-decoration: underline;\">нажмите</span> на первую кнопку, которая появляется в подходящем списке.</p></body></html>", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Память:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Память - хрупкая штуковина как и всё остальное в момент разрыва бомбы, так что будьте внимательней!</span></p></body></html>", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Нажмите правильную кнопку, чтобы перевести модуль в следующий этап. Завершите все этапы, чтобы обезвредить модуль.</p><p>- Нажатие неверной кнопки вернёт модуль на первый этап.</p><p>- Позиции кнопок отсчитываются слево направо.</p></body></html>", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Этап 1:<br/></span>Если на экране 1, нажмите кнопку на второй позиции.<br/>Если на экране 2, нажмите кнопку на второй позиции.<br/>Если на экране 3, нажмите кнопку на третьей позиции.<br/>Если на экране 4, нажмите кнопку на четвёртой позиции.<br/><br/><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Этап 2:<br/></span>Если на экране 1, нажмите кнопку со значением &quot;4&quot;.<br/>Если на экране 2, нажмите кнопку на той же позиции, которую вы нажали на 1 этапе.<br/>Если на экране 3, нажмите кнопку на первой позиции.<br/>Если на экране 4, нажмите кнопку на той же позиции, которую вы нажали на 1 этапе.</p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Этап 3:<br/></span>Если на экране 1, нажмите кнопку с тем же значением, которое вы нажали на 2 этапе.<br/>Если на экране 2, нажмите кнопку с тем же значением, которое вы нажимали на 1 этапе.<br/>Если на экране 3, нажмите кнопку на третьей позиции.<br/>Если на экране 4, нажмите кнопку со значением &quot;4&quot;.</p></body></html>", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Этап 4:</span><br/>Если на экране 1, нажмите кнопку на той же позиции, которую вы нажали на 1 этапе.<br/>Если на экране 2, нажмите кнопку на первой позиции.<br/>Если на экране 3, нажмите кнопку на той же позиции, которую вы нажали на 2 этапе.<br/>Если на экране 4, нажмите кнопку на той же позиции, которую вы нажали на 2 этапе.</p><p><br/></p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Этап 5:<br/></span>Если на экране 1, нажмите кнопку с тем же значением, которое вы нажали на 1 этапе.<br/>Если на экране 2, нажмите кнопку с тем же значением, которое вы нажали на 2 этапе.<br/>Если на экране 3, нажмите кнопку с тем же значением, которое вы нажали на 3 этапе.<br/>Если на экране 4, нажмите кнопку с тем же значением, которое вы нажали на 4 этапе.</p></body></html>", None, -1))
        self.label_50.setText(QtWidgets.QApplication.translate("MainWindow", "Память", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; text-decoration: underline;\">Память:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Устаревшая форма морского сообщения? А дальше что? Ну хотя бы это настоящая азбука Морзе, так что смотрите в оба, может, что-нибудь запомните.</span></p></body></html>", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Интерпретируйте сигнал моргающей лампочки, используя таблицу Морзе, чтобы получить одно из слов в таблице.<br/>- Сигнал зациклен и имеет большой промежуток между повторениями.</p><p>- После определения слова установите соответствующую частоту и нажмите кнопку передачи (TX)</p></body></html>", None, -1))
        self.label_54.setText(QtWidgets.QApplication.translate("MainWindow", "Азбука Морзе", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">О сложных проводах:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Эти провода не такие, как прежде. Некоторые из них полосатые! Так что они совершенно другие. Хорошо, что мы нашли краткий набор инструкций к ним! Правда, возможно, слишком краткий...</span></p></body></html>", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Посмотрите на каждый провод: над проводом есть светодиод, а под ним есть место под символ</p><p>- Для каждой связки провод-светодиод-символ используйте приведённую ниже диаграмму Венна, чтобы решить, резать провод или нет.</p><p>- Провода бывают полосатыми.</p></body></html>", None, -1))
        self.label_69.setText(QtWidgets.QApplication.translate("MainWindow", "Сложные Провода", None, -1))
        self.label_63.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">О последовательностях проводов:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Сложно сказать, как работает этот механизм. Впечатлающая проводка, но девять проводовможно расположить как-то проще.</span></p></body></html>", None, -1))
        self.label_64.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- В этом модуле несколько панелей с проводами, но единовременно видно лишь одну. Вы можете переключаться на следующую панель, используя кнопку вниз или на предыдущую, используя кнопку вверх.</p><p>- Не переходите к следующей панели, пока не будете уверены, что перерезали все необходимые провода на текущей.</p><p>- Перережьте провода, следуя приведённой ниже таблице. Появления проводов суммируются между всеми панелями в рамках одного модуля.</p></body></html>", None, -1))
        self.label_71.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Последовательности проводов</p></body></html>", None, -1))
        self.label_66.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">О лабиринтах:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Похоже на какой-то лабиринт, наверняка украденный с подноса забегаловки.</span></p></body></html>", None, -1))
        self.label_67.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Найдите лабиринт с совпадающими круглыми отметками.</p><p>- Сапёр должен провести белый огонёк до красного треугольникапри помощи кнопок со стрелками.</p><p>- <span style=\" font-weight:600;\">Осторожно</span>: не пересекайте отмеченные в лабиринте линии. Эти линии не видно на бомбе.</p></body></html>", None, -1))
        self.label_73.setText(QtWidgets.QApplication.translate("MainWindow", "Лабиринты", None, -1))
        self.label_75.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">О паролях:</span></p><p align=\"center\"><span style=\" font-style:italic;\">К счастью, пароль, кажется, не соответствует требованиям стандартов государственной безопасности: 22 символа, прописные и строчные буквы, случайные числа без палиндромов размером больше 3.</span></p></body></html>", None, -1))
        self.label_76.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Кнопки над и под каждой буквой меняют возможные буквы в одной позиции.</p><p>- Только одна комбинация доступных букв совпадёт с паролем из приведённой ниже таблицы.</p><p>- Нажмите пнопку &quot;ПРИНЯТЬ&quot; после установки подходящего слова.</p></body></html>", None, -1))
        self.label_78.setText(QtWidgets.QApplication.translate("MainWindow", "Пароли", None, -1))
        self.label_83.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">О выпуске газа:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Взлом компьютеров крайне ложен! Ну, обычно. А это смогал бы сделать даже механическая пьющая птичка, клюющая одну и ту же кнопку раз за разом.</span></p></body></html>", None, -1))
        self.label_84.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Отвечайте на вопросы компьютера кнопкой &quot;Д&quot;, если ответ &quot;да&quot;, или &quot;Н&quot;, если &quot;нет&quot;.</p></body></html>", None, -1))
        self.label_86.setText(QtWidgets.QApplication.translate("MainWindow", "Газ", None, -1))
        self.label_87.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">О разрядке конденсатора:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Мне кажется. что это здесь только для того, чтобы отвлечь нас, потому что эта инсталляция собрана крайне отвратно.</span></p></body></html>", None, -1))
        self.label_88.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Разрядите конденсатор, зажимая рычаг, прежде чем он перегрузится.</p></body></html>", None, -1))
        self.label_90.setText(QtWidgets.QApplication.translate("MainWindow", "Конденсатор", None, -1))
        self.label_91.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">О поворотных ручках:</span></p><p align=\"center\"><span style=\" font-style:italic;\">Стабильно трудно, но вечно нестабильно. Представьте, если бы все эти умения вложили во что-нибудь другое, а не безумно сложные головоломки.</span></p></body></html>", None, -1))
        self.label_92.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>- Ручку можно устанавливать в одну из четырёх позиций.<br/>- Ручка должна стоять в нужно йпозиции, когда таймер модуля достигнет нуля.<br/>- Верную позицию можно определить по состоянию вкл/выкл двенадцати светодиодов.<br/>- Позиция ручки устанавливается относительно надписи &quot;ВЕРХ&quot;, которая может быть повёрнута.</p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Оригинал", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Вниз", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Вверх", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Влево", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Вправо", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Упрощённо", None, -1))
        self.label_98.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Варианты конфигураций светодиодов:</span></p></body></html>", None, -1))
        self.label_108.setText(QtWidgets.QApplication.translate("MainWindow", "Ручка", None, -1))
        self.label_80.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Приложение А: Определение индикатора</span></p><p align=\"center\">По бокам корпуса бомбы можно обнаружить подписанные световые индиктаоры.</p></body></html>", None, -1))
        self.label_81.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Примеры индиктаоров:<br/></span><br/>- SND<br/>- CLR<br/>- CAR<br/>- IND<br/>- FRQ<br/>- SIG<br/>- NSA<br/>- MSA<br/>- TRN<br/>- BOB<br/>- FRK</p></body></html>", None, -1))
        self.label_109.setText(QtWidgets.QApplication.translate("MainWindow", "Индикатор", None, -1))
        self.label_110.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Приложение Б: определение батареи</span></p><p align=\"center\">По бокам корпуса бомбы можно обнаружить стандартные батареи.</p></body></html>", None, -1))
        self.label_112.setText(QtWidgets.QApplication.translate("MainWindow", "Батарея", None, -1))
        self.label_113.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Приложение В: определение порта</span></p><p align=\"center\">По бокам корпуса бомбы можно обнаружить цифровые и аналоговые порты.</p></body></html>", None, -1))
        self.label_115.setText(QtWidgets.QApplication.translate("MainWindow", "Порты", None, -1))
        self.pb0.setText(QtWidgets.QApplication.translate("MainWindow", "Введение", None, -1))
        self.pb2.setText(QtWidgets.QApplication.translate("MainWindow", "Кнопка", None, -1))
        self.pb3.setText(QtWidgets.QApplication.translate("MainWindow", "Клавиатура", None, -1))
        self.pb4.setText(QtWidgets.QApplication.translate("MainWindow", "Саймон", None, -1))
        self.pb6.setText(QtWidgets.QApplication.translate("MainWindow", "Память", None, -1))
        self.pb1.setText(QtWidgets.QApplication.translate("MainWindow", "Провода", None, -1))
        self.pb8.setText(QtWidgets.QApplication.translate("MainWindow", "Сл.Провода", None, -1))
        self.pb7.setText(QtWidgets.QApplication.translate("MainWindow", "Морзе", None, -1))
        self.pb13.setText(QtWidgets.QApplication.translate("MainWindow", "Конденсатор", None, -1))
        self.pb12.setText(QtWidgets.QApplication.translate("MainWindow", "Газ", None, -1))
        self.pb10.setText(QtWidgets.QApplication.translate("MainWindow", "Лабиринты", None, -1))
        self.pb9.setText(QtWidgets.QApplication.translate("MainWindow", "П. Провода", None, -1))
        self.pb11.setText(QtWidgets.QApplication.translate("MainWindow", "Пароли", None, -1))
        self.pb14.setText(QtWidgets.QApplication.translate("MainWindow", "Ручка", None, -1))
        self.pb16.setText(QtWidgets.QApplication.translate("MainWindow", "Пр. Б", None, -1))
        self.pb17.setText(QtWidgets.QApplication.translate("MainWindow", "Пр. В", None, -1))
        self.pb15.setText(QtWidgets.QApplication.translate("MainWindow", "Пр. А", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Код</span>: 317</p></body></html>", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>BD by <span style=\" text-decoration: underline;\">GAMEcraft</span> aka <span style=\" text-decoration: underline;\">Inquisitor Okabe †</span></p></body></html>", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Discord: </span><span style=\" text-decoration: underline;\">Хьюстон (Окабэ)#8632</span></p></body></html>", None, -1))
        self.pbDiscord.setText(QtWidgets.QApplication.translate("MainWindow", "Зайти в Discord", None, -1))
        self.pb5.setText(QtWidgets.QApplication.translate("MainWindow", "Слова", None, -1))
        self.lb0.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">0.</p></body></html>", None, -1))
        self.lb1.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">1.</p></body></html>", None, -1))
        self.lb2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">2.</p></body></html>", None, -1))
        self.lb3.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">3.</p></body></html>", None, -1))
        self.lb4.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">4.</p></body></html>", None, -1))
        self.lb5.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">5.</p></body></html>", None, -1))
        self.lb8.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">8.</p></body></html>", None, -1))
        self.lb9.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">9.</p></body></html>", None, -1))
        self.lb6.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">6.</p></body></html>", None, -1))
        self.lb7.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">7.</p></body></html>", None, -1))
        self.lb12.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">12.</p></body></html>", None, -1))
        self.lb17.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">17.</p></body></html>", None, -1))
        self.lb13.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">13.</p></body></html>", None, -1))
        self.lb10.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">10.</p></body></html>", None, -1))
        self.lb11.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">11.</p></body></html>", None, -1))
        self.lb15.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">15.</p></body></html>", None, -1))
        self.lb16.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">16.</p></body></html>", None, -1))
        self.lb14.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">14.</p></body></html>", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

