# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui',
# licensing of 'untitled.ui' applies.
#
# Created: Sat May 15 14:37:08 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 315)
        Form.setMinimumSize(QtCore.QSize(378, 315))
        Form.setMaximumSize(QtCore.QSize(378, 315))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("S;GFG.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 361, 161))
        self.groupBox.setObjectName("groupBox")
        self.entry_mmoney = QtWidgets.QLineEdit(self.groupBox)
        self.entry_mmoney.setGeometry(QtCore.QRect(10, 20, 80, 20))
        self.entry_mmoney.setObjectName("entry_mmoney")
        self.entry_smoney = QtWidgets.QLineEdit(self.groupBox)
        self.entry_smoney.setGeometry(QtCore.QRect(10, 41, 80, 20))
        self.entry_smoney.setObjectName("entry_smoney")
        self.entry_emoney = QtWidgets.QLineEdit(self.groupBox)
        self.entry_emoney.setGeometry(QtCore.QRect(10, 62, 80, 20))
        self.entry_emoney.setObjectName("entry_emoney")
        self.entry_gmoney = QtWidgets.QLineEdit(self.groupBox)
        self.entry_gmoney.setGeometry(QtCore.QRect(10, 83, 80, 20))
        self.entry_gmoney.setObjectName("entry_gmoney")
        self.entry_pmoney = QtWidgets.QLineEdit(self.groupBox)
        self.entry_pmoney.setGeometry(QtCore.QRect(10, 104, 80, 20))
        self.entry_pmoney.setObjectName("entry_pmoney")
        self.label_mm = QtWidgets.QLabel(self.groupBox)
        self.label_mm.setGeometry(QtCore.QRect(172, 20, 80, 20))
        self.label_mm.setFrameShape(QtWidgets.QFrame.Box)
        self.label_mm.setObjectName("label_mm")
        self.label_sm = QtWidgets.QLabel(self.groupBox)
        self.label_sm.setGeometry(QtCore.QRect(172, 41, 80, 20))
        self.label_sm.setFrameShape(QtWidgets.QFrame.Box)
        self.label_sm.setObjectName("label_sm")
        self.label_em = QtWidgets.QLabel(self.groupBox)
        self.label_em.setGeometry(QtCore.QRect(172, 62, 80, 20))
        self.label_em.setFrameShape(QtWidgets.QFrame.Box)
        self.label_em.setObjectName("label_em")
        self.label_gm = QtWidgets.QLabel(self.groupBox)
        self.label_gm.setGeometry(QtCore.QRect(172, 83, 80, 20))
        self.label_gm.setFrameShape(QtWidgets.QFrame.Box)
        self.label_gm.setObjectName("label_gm")
        self.label_pm = QtWidgets.QLabel(self.groupBox)
        self.label_pm.setGeometry(QtCore.QRect(172, 104, 80, 20))
        self.label_pm.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pm.setObjectName("label_pm")
        self.run_money = QtWidgets.QPushButton(self.groupBox)
        self.run_money.setGeometry(QtCore.QRect(95, 130, 75, 23))
        self.run_money.setObjectName("run_money")
        self.reset_money = QtWidgets.QPushButton(self.groupBox)
        self.reset_money.setGeometry(QtCore.QRect(10, 130, 23, 23))
        self.reset_money.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_money.setIcon(icon1)
        self.reset_money.setObjectName("reset_money")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(91, 41, 80, 20))
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(91, 104, 80, 20))
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(91, 20, 80, 20))
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(91, 83, 80, 20))
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(91, 62, 80, 20))
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.trader_gm = QtWidgets.QLineEdit(self.groupBox)
        self.trader_gm.setEnabled(False)
        self.trader_gm.setGeometry(QtCore.QRect(253, 83, 80, 20))
        self.trader_gm.setObjectName("trader_gm")
        self.trader_sm = QtWidgets.QLineEdit(self.groupBox)
        self.trader_sm.setEnabled(False)
        self.trader_sm.setGeometry(QtCore.QRect(253, 41, 80, 20))
        self.trader_sm.setObjectName("trader_sm")
        self.trader_em = QtWidgets.QLineEdit(self.groupBox)
        self.trader_em.setEnabled(False)
        self.trader_em.setGeometry(QtCore.QRect(253, 62, 80, 20))
        self.trader_em.setObjectName("trader_em")
        self.trader_pm = QtWidgets.QLineEdit(self.groupBox)
        self.trader_pm.setEnabled(False)
        self.trader_pm.setGeometry(QtCore.QRect(253, 104, 80, 20))
        self.trader_pm.setObjectName("trader_pm")
        self.trader_mm = QtWidgets.QLineEdit(self.groupBox)
        self.trader_mm.setEnabled(False)
        self.trader_mm.setGeometry(QtCore.QRect(253, 20, 80, 20))
        self.trader_mm.setObjectName("trader_mm")
        self.mode_switcher = QtWidgets.QCheckBox(self.groupBox)
        self.mode_switcher.setGeometry(QtCore.QRect(293, 133, 20, 20))
        self.mode_switcher.setText("")
        self.mode_switcher.setChecked(False)
        self.mode_switcher.setTristate(True)
        self.mode_switcher.setObjectName("mode_switcher")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(310, 130, 23, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 347, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.entry_km = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_km.setGeometry(QtCore.QRect(95, 40, 80, 20))
        self.entry_km.setObjectName("entry_km")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 84, 20))
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.entry_mi = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_mi.setGeometry(QtCore.QRect(176, 40, 80, 20))
        self.entry_mi.setObjectName("entry_mi")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(257, 40, 84, 20))
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.entry_sm = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_sm.setGeometry(QtCore.QRect(95, 61, 80, 20))
        self.entry_sm.setObjectName("entry_sm")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(257, 61, 84, 20))
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.entry_in = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_in.setGeometry(QtCore.QRect(176, 61, 80, 20))
        self.entry_in.setObjectName("entry_in")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 61, 84, 20))
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.entry_kg = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_kg.setGeometry(QtCore.QRect(95, 82, 80, 20))
        self.entry_kg.setObjectName("entry_kg")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(257, 82, 84, 20))
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.entry_lb = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_lb.setGeometry(QtCore.QRect(176, 82, 80, 20))
        self.entry_lb.setObjectName("entry_lb")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 82, 84, 20))
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.reset_other = QtWidgets.QPushButton(self.groupBox_2)
        self.reset_other.setGeometry(QtCore.QRect(10, 110, 23, 23))
        self.reset_other.setText("")
        self.reset_other.setIcon(icon1)
        self.reset_other.setObjectName("reset_other")
        self.left_other = QtWidgets.QPushButton(self.groupBox_2)
        self.left_other.setGeometry(QtCore.QRect(98, 110, 75, 23))
        self.left_other.setObjectName("left_other")
        self.right_other = QtWidgets.QPushButton(self.groupBox_2)
        self.right_other.setGeometry(QtCore.QRect(179, 110, 75, 23))
        self.right_other.setObjectName("right_other")
        self.entry_m = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_m.setGeometry(QtCore.QRect(95, 19, 80, 20))
        self.entry_m.setObjectName("entry_m")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(257, 19, 84, 20))
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.entry_ft = QtWidgets.QLineEdit(self.groupBox_2)
        self.entry_ft.setGeometry(QtCore.QRect(176, 19, 80, 20))
        self.entry_ft.setObjectName("entry_ft")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 19, 84, 20))
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "DnD Multy Converter", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Монеты", None, -1))
        self.entry_mmoney.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.entry_smoney.setText(QtWidgets.QApplication.translate("Form", "10", None, -1))
        self.entry_emoney.setText(QtWidgets.QApplication.translate("Form", "50", None, -1))
        self.entry_gmoney.setText(QtWidgets.QApplication.translate("Form", "100", None, -1))
        self.entry_pmoney.setText(QtWidgets.QApplication.translate("Form", "1000", None, -1))
        self.label_mm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_sm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_em.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_gm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_pm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.run_money.setText(QtWidgets.QApplication.translate("Form", "Посчитать", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>серебро <span style=\" font-weight:600;\">(см)</span></p></body></html>", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>платина <span style=\" font-weight:600;\">(пм)</span></p></body></html>", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>медь <span style=\" font-weight:600;\">(мм)</span></p></body></html>", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>золото <span style=\" font-weight:600;\">(зм)</span></p></body></html>", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>электрум <span style=\" font-weight:600;\">(эм)</span></p></body></html>", None, -1))
        self.trader_gm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.trader_sm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.trader_em.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.trader_pm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.trader_mm.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.pushButton.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Выкл. - Режим конвертера: </span>Просто переводит введённые монеты в другие.<br/><span style=\" font-weight:600;\">Вкл. - Режим сдачи:</span> При переводе монет учитывается количество валюты у торговца, которой он может разменять сдачу.</p></body></html>", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "?", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "Прочее", None, -1))
        self.entry_km.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">(км)</span> километр</p></body></html>", None, -1))
        self.entry_mi.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>миля <span style=\" font-weight:600;\">(mi)</span></p></body></html>", None, -1))
        self.entry_sm.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>дюйм <span style=\" font-weight:600;\">(in)</span></p></body></html>", None, -1))
        self.entry_in.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">(см)</span> сантиметр</p></body></html>", None, -1))
        self.entry_kg.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>фунт <span style=\" font-weight:600;\">(lb)</span></p></body></html>", None, -1))
        self.entry_lb.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">(кг)</span> килограмм</p></body></html>", None, -1))
        self.left_other.setText(QtWidgets.QApplication.translate("Form", "Посчитать >", None, -1))
        self.right_other.setText(QtWidgets.QApplication.translate("Form", "< Посчитать", None, -1))
        self.entry_m.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>фут <span style=\" font-weight:600;\">(ft)</span></p></body></html>", None, -1))
        self.entry_ft.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">(м)</span> метр</p></body></html>", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

